// -*- mode: c++ -*-
// 
// File pca.C generated by TPrincipal::MakeCode
// on Mon Aug  7 14:33:53 2023
// ROOT version 6.18/04
//
// This file contains the functions 
//
//    void  X2P(Double_t *x, Double_t *p); 
//    void  P2X(Double_t *p, Double_t *x, Int_t nTest);
//
// The first for transforming original data x in 
// pattern space, to principal components p in 
// feature space. The second function is for the
// inverse transformation, but using only nTest
// of the principal components in the expansion
// 
// See TPrincipal class documentation for more information 
// 
#ifndef __CINT__
#include <Rtypes.h> // needed for Double_t etc
#endif

//
// Static data variables
//
static Int_t    gNVariables = 10;

// Assignment of eigenvector matrix.
// Elements are stored row-wise, that is
//    M[i][j] = e[i * nVariables + j] 
// where i and j are zero-based
static Double_t gEigenVectors[] = {
  -0.013515,
  0.321659,
  -0.309968,
  -0.468151,
  -0.45895,
  0.0406555,
  -0.578713,
  -0.184148,
  -9.69978e-07,
  4.03923e-06,
  -0.00215452,
  0.464797,
  0.13683,
  -0.0294559,
  -0.179853,
  -0.736225,
  0.372088,
  -0.227036,
  3.90203e-06,
  6.53048e-07,
  0.00283089,
  -0.443359,
  -0.132333,
  -0.634288,
  0.202657,
  -0.0129473,
  0.329684,
  -0.483386,
  -5.82948e-06,
  5.19371e-06,
  -0.00768721,
  -0.0795161,
  -0.605333,
  0.571913,
  -0.165195,
  0.0682218,
  0.11409,
  -0.505119,
  -7.05759e-07,
  -1.17571e-06,
  -0.00324782,
  -0.221687,
  0.696302,
  0.183711,
  -0.333951,
  0.116809,
  -0.208249,
  -0.51354,
  1.59005e-06,
  2.4051e-06,
  -0.00227931,
  0.472919,
  0.096584,
  -0.117482,
  -0.205129,
  0.654064,
  0.530121,
  -0.0480139,
  -8.42587e-06,
  -5.34913e-07,
  0.00171942,
  -0.452506,
  -0.0840331,
  -0.0548488,
  -0.731424,
  -0.100257,
  0.283704,
  0.399557,
  -5.8744e-06,
  -3.48066e-06,
  0.577271,
  0.00411573,
  -0.003204,
  0.00013326,
  -0.00504144,
  0.000905869,
  -0.0040577,
  -0.00459008,
  0.123271,
  0.807137,
  0.577271,
  0.0041147,
  -0.00320442,
  0.000123741,
  -0.0050421,
  0.000909545,
  -0.0040574,
  -0.00459706,
  0.637366,
  -0.510325,
  0.577271,
  0.00411811,
  -0.00320065,
  0.000132169,
  -0.0050365,
  0.00089893,
  -0.00406593,
  -0.00459631,
  -0.760637,
  -0.296813};

// Assignment to eigen value vector. Zero-based.
static Double_t gEigenValues[] = {
  0.300055,
  0.103257,
  0.101652,
  0.100815,
  0.100035,
  0.0994254,
  0.0982075,
  0.0965544,
  2.27585e-08,
  6.68928e-09
};

// Assignment to mean value vector. Zero-based.
static Double_t gMeanValues[] = {
  5.0082,
  7.9976,
  1.96735,
  5.0162,
  8.0087,
  2.01253,
  4.99247,
  175147,
  150188,
  140110
};

// Assignment to sigma value vector. Zero-based.
static Double_t gSigmaValues[] = {
  1.00507,
  2.86056,
  1.95587,
  1.00527,
  2.83895,
  1.97263,
  1.01426,
  101004,
  86583.5,
  80794.3
};

// 
// The function   void X2P(Double_t *x, Double_t *p)
// 
void X2P(Double_t *x, Double_t *p) {
  for (Int_t i = 0; i < gNVariables; i++) {
    p[i] = 0;
    for (Int_t j = 0; j < gNVariables; j++)
      p[i] += (x[j] - gMeanValues[j]) 
        * gEigenVectors[j *  gNVariables + i] / gSigmaValues[j];

  }
}

// 
// The function   void P2X(Double_t *p, Double_t *x, Int_t nTest)
// 
void P2X(Double_t *p, Double_t *x, Int_t nTest) {
  for (Int_t i = 0; i < gNVariables; i++) {
    x[i] = gMeanValues[i];
    for (Int_t j = 0; j < nTest; j++)
      x[i] += p[j] * gSigmaValues[i] 
        * gEigenVectors[i *  gNVariables + j];
  }
}

// EOF for pca.C
